include_guard(GLOBAL)

function(utils_check_required)
    foreach(__var ${ARGN})
        if(NOT DEFINED ${__var})
            message(FATAL_ERROR "Missing required variable: ${__var}")
        endif()
    endforeach()
endfunction()

function(utils_check_enum_entry ENTRY_NAME ENUM_NAME)
    if(NOT ${ENTRY_NAME} IN_LIST ENUM_NAME)
        message(FATAL_ERROR "Incorrect value \"${ENTRY_NAME}\" - must be one of ${ENUM_NAME}")
    endif()
endfunction()

macro(utils_parse_arguments ARG_NAME OPTIONS SINGLE_REQUIRED SINGLE_OPTIONAL MULTI)
    cmake_parse_arguments(${ARG_NAME} "${OPTIONS}" "${SINGLE_REQUIRED};${SINGLE_OPTIONAL}" "${MULTI}" ${ARGN})
    if(${ARG_NAME}_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Invalid arguments: ${${ARG_NAME}_UNPARSED_ARGUMENTS}")
    endif()
    foreach(__arg ${__single_required})
        utils_check_required("${ARG_NAME}_${__arg}")
    endforeach()
endmacro()
